### ISSUE TITLE
V2 Onion addressing - Deprecation and impending removal from Tor's soruce Code

### ISSUE THREAD

**Issue by bakertaylor28** [rahra/onioncat#32] opened 2021-06-03 21:43 UTC
Tor Project has indicated that, as of October 2021, V2 onion services will in fact be disabled in the source code, and they are currently deprecated. The Tor project has advised, as of June 02, 2021 that ALL V2s need to transition / migrate to  V3 addressing immediately. **See** e.g. https://blog.torproject.org/new-release-tor-browser-10017 , etc.

**Comment by rahra** [comment] 2021-06-04 07:35
Yes, I know.
Onioncat is well aware of V3. Please read this article: https://www.onioncat.org/2019/08/onioncat-and-tor-hidden-services-v3/
It does not work out of the box as nicely as it does with V2 but it still works with setting up a lookup database. This comes with the nature of longer hashes.
There are ideas for the future, such as adding the lookup service into Tor's HS directories.

**Comment by rahra** [comment] 2021-06-04 07:37
I close this since it is a duplicate of #31 .

**Closed by rahra** 2021-06-04 07:37 UTC
